# Loads default set of integrations. Do not remove.
default_config: {}

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 0.0.0.0/0
      allow_bypass_login: true
    - type: homeassistant

logger:
  default: warn
  logs:
    homeassistant.helpers.entity: debug
    custom_components: debug
    homeassistant.components.sensor: debug
    custom_components.ziggo_modem.sensor: debug

ziggo_modem:
  default_gateway: !secret default_gateway
  router_password: !secret router_password

sensor:
  - platform: ziggo_modem
